# Generated by Django 4.2 on 2025-07-21 21:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador del sistema'), ('MANAGER', 'Gestor de procesos'), ('PARTICIPANT', 'Participante de la operación')], max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MacroProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_suffix', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_suffix', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('macro_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='processes.macroprocess')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('macro_process', 'code_suffix')},
            },
        ),
        migrations.CreateModel(
            name='ProcessInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocess_templates', to='processes.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'En ejecución'), ('COMPLETED', 'Completado')], default='ACTIVE', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.career')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.academicperiod')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='processes.subprocesstemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('permanent', models.BooleanField(default=True)),
                ('subprocess_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_types', to='processes.subprocesstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OperationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('COMPLETE', 'Marcar como completada'), ('DOC_REQUEST', 'Solicitud de documento'), ('REVIEW', 'Revisión y aprobación'), ('CERT_REQUEST', 'Solicitud de certificado')], max_length=15)),
                ('order', models.PositiveSmallIntegerField(help_text='Secuencia dentro del subproceso')),
                ('deadline_days', models.PositiveSmallIntegerField(default=0)),
                ('requires_approval', models.BooleanField(default=False)),
                ('storage_type', models.ForeignKey(blank=True, help_text='Si aplica, tipo de almacenamiento asociado al documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.storagetype')),
                ('subprocess_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_templates', to='processes.subprocesstemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('subprocess_template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OperationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('LATE', 'Atrasado'), ('COMPLETED', 'Completado')], default='PENDING', max_length=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('operation_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processes.operationtemplate')),
                ('subprocess_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_instances', to='processes.subprocessinstance')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('subprocess_instance', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OperationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_operation', models.CharField(choices=[('EMITTER', 'Emisor'), ('RECEIVER', 'Receptor'), ('RESPONSIBLE', 'Responsable')], default='RESPONSIBLE', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')], default='PENDING', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='processes.operationinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationActorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador del sistema'), ('MANAGER', 'Gestor de procesos'), ('PARTICIPANT', 'Participante de la operación')], max_length=12)),
                ('is_emitter', models.BooleanField(default=False)),
                ('is_receiver', models.BooleanField(default=False)),
                ('operation_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_templates', to='processes.operationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.operationassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='macroprocess',
            name='process_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macroprocesses', to='processes.processinstitution'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('operation_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='processes.operationinstance')),
                ('replaced_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.document')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processes.storagetype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='macroprocess',
            unique_together={('process_institution', 'code_suffix')},
        ),
    ]
