# Generated by Django 4.2 on 2025-07-21 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storagetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='macroprocess',
            name='code_suffix',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='storage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.storagetype'),
        ),
        migrations.AlterField(
            model_name='process',
            name='code_suffix',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
