# Generated by Django 4.2 on 2026-06-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0003_operationactortemplate_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
